ERROR - 2025-06-07 17:34:55 --> Datos recibidos: Array
(
    [nombre] => Camiseta de Prueba
    [descripcion] => 100% algodón
    [precio] => 29.99
    [stock] => 50
    [talla] => M
    [color] => Blanco
)

ERROR - 2025-06-07 17:34:55 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'proyecto_cf'@'localhost' (using password: YES) in D:\xampp\htdocs\proyecto_taller\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\xampp\htdocs\proyecto_taller\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'proyecto_cf', Object(SensitiveParameterValue), 'costura_fina', 3306, '', 0)
#1 D:\xampp\htdocs\proyecto_taller\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\proyecto_taller\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\proyecto_taller\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 D:\xampp\htdocs\proyecto_taller\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\proyecto_taller\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\proyecto_taller\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\proyecto_taller\app\Controllers\ProductoController.php(31): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(933): App\Controllers\ProductoController->crear()
#9 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoController))
#10 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\proyecto_taller\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\proyecto_taller\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\xampp\htdocs\proyecto_taller\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\proyecto_taller\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\xampp\htdocs\proyecto_taller\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\proyecto_taller\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\proyecto_taller\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#3 D:\xampp\htdocs\proyecto_taller\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 D:\xampp\htdocs\proyecto_taller\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#5 D:\xampp\htdocs\proyecto_taller\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 D:\xampp\htdocs\proyecto_taller\app\Controllers\ProductoController.php(31): CodeIgniter\Model->insert(Array)
#7 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(933): App\Controllers\ProductoController->crear()
#8 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoController))
#9 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\proyecto_taller\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\proyecto_taller\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\xampp\htdocs\proyecto_taller\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-06-07 17:34:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: productos/crear]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `productos` (`nombre`, `descripcion`, `precio`, `stock`, `talla`, `color`) VALUES (:nombre:, :descripcion:, :precio:, :stock:, :talla:, :color:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\ProductoController.php(31): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ProductoController->crear()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-07 18:43:35 --> Datos recibidos: Array
(
    [nombre] => Camiseta de Prueba
    [descripcion] => 100% algodón
    [precio] => 29.99
    [stock] => 50
    [talla] => M
    [color] => Blanco
)

ERROR - 2025-06-07 18:43:35 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'proyecto_cf'@'localhost' (using password: YES) in D:\xampp\htdocs\proyecto_taller\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\xampp\htdocs\proyecto_taller\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'proyecto_cf', Object(SensitiveParameterValue), 'costura_fina', 3306, '', 0)
#1 D:\xampp\htdocs\proyecto_taller\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\proyecto_taller\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\proyecto_taller\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 D:\xampp\htdocs\proyecto_taller\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\proyecto_taller\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\proyecto_taller\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\proyecto_taller\app\Controllers\ProductoController.php(31): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(933): App\Controllers\ProductoController->crear()
#9 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoController))
#10 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\proyecto_taller\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\proyecto_taller\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\xampp\htdocs\proyecto_taller\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\proyecto_taller\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\xampp\htdocs\proyecto_taller\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\proyecto_taller\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\proyecto_taller\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#3 D:\xampp\htdocs\proyecto_taller\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 D:\xampp\htdocs\proyecto_taller\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#5 D:\xampp\htdocs\proyecto_taller\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 D:\xampp\htdocs\proyecto_taller\app\Controllers\ProductoController.php(31): CodeIgniter\Model->insert(Array)
#7 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(933): App\Controllers\ProductoController->crear()
#8 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoController))
#9 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\proyecto_taller\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\proyecto_taller\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\xampp\htdocs\proyecto_taller\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-06-07 18:43:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: productos/crear]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `productos` (`nombre`, `descripcion`, `precio`, `stock`, `talla`, `color`) VALUES (:nombre:, :descripcion:, :precio:, :stock:, :talla:, :color:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\ProductoController.php(31): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ProductoController->crear()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-07 19:28:52 --> Datos recibidos: Array
(
    [nombre] => Camiseta de Prueba
    [descripcion] => 100% algodón
    [precio] => 29.99
    [stock] => 50
    [talla] => M
    [color] => Blanco
)

ERROR - 2025-06-07 19:28:52 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'proyecto_cf'@'localhost' (using password: YES) in D:\xampp\htdocs\proyecto_taller\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\xampp\htdocs\proyecto_taller\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'proyecto_cf', Object(SensitiveParameterValue), 'costura_fina', 3306, '', 0)
#1 D:\xampp\htdocs\proyecto_taller\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\proyecto_taller\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\proyecto_taller\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 D:\xampp\htdocs\proyecto_taller\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\proyecto_taller\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\proyecto_taller\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\proyecto_taller\app\Controllers\ProductoController.php(31): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(933): App\Controllers\ProductoController->crear()
#9 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoController))
#10 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\proyecto_taller\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\proyecto_taller\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\xampp\htdocs\proyecto_taller\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\proyecto_taller\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\xampp\htdocs\proyecto_taller\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\proyecto_taller\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\proyecto_taller\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#3 D:\xampp\htdocs\proyecto_taller\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 D:\xampp\htdocs\proyecto_taller\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#5 D:\xampp\htdocs\proyecto_taller\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 D:\xampp\htdocs\proyecto_taller\app\Controllers\ProductoController.php(31): CodeIgniter\Model->insert(Array)
#7 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(933): App\Controllers\ProductoController->crear()
#8 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoController))
#9 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\proyecto_taller\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\proyecto_taller\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\xampp\htdocs\proyecto_taller\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-06-07 19:28:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: productos/crear]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `productos` (`nombre`, `descripcion`, `precio`, `stock`, `talla`, `color`) VALUES (:nombre:, :descripcion:, :precio:, :stock:, :talla:, :color:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\ProductoController.php(31): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ProductoController->crear()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-07 19:54:39 --> Datos recibidos: Array
(
    [nombre] => Camiseta de Prueba
    [descripcion] => 100% algodón
    [precio] => 29.99
    [stock] => 50
    [talla] => M
    [color] => Blanco
)

ERROR - 2025-06-07 19:54:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'proyecto_cf'@'localhost' (using password: YES) in D:\xampp\htdocs\proyecto_taller\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\xampp\htdocs\proyecto_taller\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'proyecto_cf', Object(SensitiveParameterValue), 'costura_fina', 3306, '', 0)
#1 D:\xampp\htdocs\proyecto_taller\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\proyecto_taller\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\proyecto_taller\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 D:\xampp\htdocs\proyecto_taller\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\proyecto_taller\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\proyecto_taller\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\proyecto_taller\app\Controllers\ProductoController.php(31): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(933): App\Controllers\ProductoController->crear()
#9 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoController))
#10 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\proyecto_taller\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\proyecto_taller\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\xampp\htdocs\proyecto_taller\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\proyecto_taller\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\xampp\htdocs\proyecto_taller\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\proyecto_taller\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\proyecto_taller\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#3 D:\xampp\htdocs\proyecto_taller\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 D:\xampp\htdocs\proyecto_taller\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#5 D:\xampp\htdocs\proyecto_taller\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 D:\xampp\htdocs\proyecto_taller\app\Controllers\ProductoController.php(31): CodeIgniter\Model->insert(Array)
#7 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(933): App\Controllers\ProductoController->crear()
#8 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoController))
#9 D:\xampp\htdocs\proyecto_taller\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\proyecto_taller\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\proyecto_taller\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\xampp\htdocs\proyecto_taller\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-06-07 19:54:41 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: productos/crear]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `productos` (`nombre`, `descripcion`, `precio`, `stock`, `talla`, `color`) VALUES (:nombre:, :descripcion:, :precio:, :stock:, :talla:, :color:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\ProductoController.php(31): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ProductoController->crear()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
